# Generated by Django 2.1 on 2018-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('default_status', models.BooleanField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
