# Generated by Django 2.1 on 2018-09-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0002_dashuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashuser',
            old_name='appnames',
            new_name='appgrid',
        ),
    ]
